site_name: conda-pack
site_url: https://slaclab.github.io/conda-pack-docs
repo_url: https://github.com/slaclab/conda-pack-docs
nav:
  - Overview: index.md
  - Github Actions: action.md
  - Docker: docker.md
  - Tests: tests.md
  - Issues: issues.md
theme:
  name: material
